import { describe, test, expect } from "bun:test";
import { compile } from "../../src/compiler.ts";
import { generateLuau } from "../../src/codegen/luau.ts";
import { generateRBXMX } from "../../src/codegen/rbxmx.ts";
import { readFileSync } from "fs";
import { join } from "path";

const INPUT_CSS = readFileSync(
  join(import.meta.dir, "../fixtures/full-example.css"),
  "utf-8",
);

describe("full spec example", () => {
  const result = compile(
    [{ filename: "styles.css", content: INPUT_CSS }],
    { name: "StyleSheet", warnLevel: "all", strict: false },
  );

  test("extracts 5 tokens from :root", () => {
    expect(result.ir.tokens.size).toBe(5);
    expect(result.ir.tokens.has("bg")).toBe(true);
    expect(result.ir.tokens.has("text")).toBe(true);
    expect(result.ir.tokens.has("primary")).toBe(true);
    expect(result.ir.tokens.has("radius")).toBe(true);
    expect(result.ir.tokens.has("gap")).toBe(true);
  });

  test("token types are correct", () => {
    expect(result.ir.tokens.get("bg")!.type).toBe("Color3");
    expect(result.ir.tokens.get("text")!.type).toBe("Color3");
    expect(result.ir.tokens.get("primary")!.type).toBe("Color3");
    expect(result.ir.tokens.get("radius")!.type).toBe("UDim");
    expect(result.ir.tokens.get("gap")!.type).toBe("UDim");
  });

  test("produces 12 IR rules", () => {
    expect(result.ir.rules.length).toBe(12);
  });

  test("maps selectors correctly", () => {
    const selectors = result.ir.rules.map((r) => r.selector);
    expect(selectors).toContain("Frame");
    expect(selectors).toContain(".card");
    expect(selectors).toContain(".card::UICorner");
    expect(selectors).toContain(".card::UIStroke");
    expect(selectors).toContain(".card::UIPadding");
    expect(selectors).toContain(".card::UIListLayout");
    expect(selectors).toContain(".card:Hover");
    expect(selectors).toContain(".card > TextLabel");
    expect(selectors).toContain("TextButton.primary");
    expect(selectors).toContain("TextButton.primary::UICorner");
    expect(selectors).toContain("TextButton.primary::UIPadding");
    expect(selectors).toContain("TextButton.primary:Hover");
  });

  test("Luau output contains expected patterns", () => {
    const luau = generateLuau(result.ir, {
      minify: false,
      sourceFile: "styles.css",
    });

    // Header
    expect(luau).toContain("-- Auto-generated by rbx-css");
    expect(luau).toContain("-- Source: styles.css");

    // Tokens
    expect(luau).toContain('sheet:SetAttribute("bg", Color3.fromHex("#1a1a2e"))');
    expect(luau).toContain('sheet:SetAttribute("radius", UDim.new(0, 8))');
    expect(luau).toContain('sheet:SetAttribute("gap", UDim.new(0, 12))');

    // Frame rule (mapped from 'div')
    expect(luau).toContain('rule.Selector = "Frame"');
    expect(luau).toContain('"BackgroundColor3", "$bg"');

    // .card::UICorner with token reference
    expect(luau).toContain('rule.Selector = ".card::UICorner"');
    expect(luau).toContain('"$radius"');

    // .card::UIStroke
    expect(luau).toContain('rule.Selector = ".card::UIStroke"');
    expect(luau).toContain("Thickness = 1");
    expect(luau).toContain("Color3.fromRGB(255, 255, 255)");
    expect(luau).toContain("Enum.ApplyStrokeMode.Border");

    // .card::UIPadding
    expect(luau).toContain('rule.Selector = ".card::UIPadding"');
    expect(luau).toContain("PaddingTop = UDim.new(0, 16)");

    // .card::UIListLayout
    expect(luau).toContain('rule.Selector = ".card::UIListLayout"');
    expect(luau).toContain("Enum.FillDirection.Vertical");
    expect(luau).toContain('"$gap"');

    // Hover state
    expect(luau).toContain('rule.Selector = ".card:Hover"');
    expect(luau).toContain("Color3.fromRGB(42, 42, 78)");

    // Child selector with element mapping
    expect(luau).toContain('rule.Selector = ".card > TextLabel"');
    expect(luau).toContain('"$text"');
    expect(luau).toContain("TextSize = 18");
    expect(luau).toContain("Enum.FontWeight.Bold");
    expect(luau).toContain("GothamSSm.json");

    // Compound selector: button.primary -> TextButton.primary
    expect(luau).toContain('rule.Selector = "TextButton.primary"');
    expect(luau).toContain('"$primary"');
    expect(luau).toContain("Color3.fromRGB(255, 255, 255)");
    expect(luau).toContain("TextSize = 16");
    expect(luau).toContain("Enum.AutomaticSize.XY");

    // TextButton.primary::UICorner
    expect(luau).toContain('rule.Selector = "TextButton.primary::UICorner"');
    expect(luau).toContain("UDim.new(0, 6)");

    // TextButton.primary::UIPadding
    expect(luau).toContain("PaddingTop = UDim.new(0, 8)");
    expect(luau).toContain("PaddingLeft = UDim.new(0, 24)");

    // TextButton.primary:Hover
    expect(luau).toContain('rule.Selector = "TextButton.primary:Hover"');
    expect(luau).toContain("Color3.fromRGB(68, 112, 255)");

    // Module structure
    expect(luau).toContain("return createStyleSheet");
  });

  test("RBXMX output is valid XML structure", () => {
    const rbxmx = generateRBXMX(result.ir);
    expect(rbxmx).toContain('<roblox version="4">');
    expect(rbxmx).toContain('class="StyleSheet"');
    expect(rbxmx).toContain('class="StyleRule"');
    expect(rbxmx).toContain("</roblox>");
    expect(rbxmx).toContain("Frame");
    expect(rbxmx).toContain(".card");
    expect(rbxmx).toContain("TextButton.primary");
  });
});

describe("theme compilation", () => {
  const INPUT = readFileSync(
    join(import.meta.dir, "../fixtures/themes.css"),
    "utf-8",
  );

  const result = compile(
    [{ filename: "themes.css", content: INPUT }],
    { name: "StyleSheet", warnLevel: "all", strict: false },
  );

  test("extracts base tokens", () => {
    expect(result.ir.tokens.size).toBe(2);
    expect(result.ir.tokens.has("bg")).toBe(true);
    expect(result.ir.tokens.has("text")).toBe(true);
  });

  test("extracts dark theme", () => {
    expect(result.ir.themes).toBeDefined();
    expect(result.ir.themes!.has("dark")).toBe(true);
  });

  test("dark theme has correct tokens", () => {
    const dark = result.ir.themes!.get("dark")!;
    expect(dark.tokens.has("bg")).toBe(true);
    expect(dark.tokens.has("text")).toBe(true);
    expect(dark.tokens.has("accent")).toBe(true);
  });

  test("base tokens are not polluted by theme tokens", () => {
    expect(result.ir.tokens.has("accent")).toBe(false);
  });

  test("Luau output includes theme boilerplate", () => {
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("local themes = {}");
    expect(luau).toContain('theme.Name = "StyleSheet_dark"');
    expect(luau).toContain("StyleDerive");
    expect(luau).toContain("local function setTheme(themeName: string)");
    expect(luau).toContain("themeDerive.StyleSheet = themes[themeName]");
  });
});

describe("multi-file merge", () => {
  test("merges tokens and rules from multiple files", () => {
    const css1 = `:root { --primary: #335fff; } .a { color: white; }`;
    const css2 = `.b { color: black; }`;

    const result = compile(
      [
        { filename: "a.css", content: css1 },
        { filename: "b.css", content: css2 },
      ],
      { name: "Merged", warnLevel: "none", strict: false },
    );

    expect(result.ir.tokens.has("primary")).toBe(true);
    expect(result.ir.rules.length).toBe(2);
    expect(result.ir.rules[0]!.selector).toBe(".a");
    expect(result.ir.rules[1]!.selector).toBe(".b");
  });
});

describe("empty CSS", () => {
  test("produces empty StyleSheet", () => {
    const result = compile(
      [{ filename: "empty.css", content: "" }],
      { name: "Empty", warnLevel: "all", strict: false },
    );

    expect(result.ir.tokens.size).toBe(0);
    expect(result.ir.rules.length).toBe(0);
  });
});
