import type {
  StyleSheetIR,
  StyleRuleIR,
  RobloxValue,
  TokenValue,
} from "../ir/types.ts";
import { rgbToHex } from "../mappers/colors.ts";

export interface LuauOptions {
  minify: boolean;
  sourceFile?: string;
}

export function generateLuau(ir: StyleSheetIR, options: LuauOptions): string {
  const lines: string[] = [];
  const t = options.minify ? "" : "    ";

  if (!options.minify) {
    lines.push("-- Auto-generated by rbx-css");
    if (options.sourceFile) {
      lines.push(`-- Source: ${options.sourceFile}`);
    }
    lines.push("");
  }

  lines.push("local function createStyleSheet()");
  lines.push(`${t}local sheet = Instance.new("StyleSheet")`);
  lines.push(`${t}sheet.Name = ${luauStr(ir.name)}`);
  lines.push("");

  // Tokens
  if (ir.tokens.size > 0) {
    lines.push(`${t}-- Tokens from :root`);
    for (const [name, value] of ir.tokens) {
      lines.push(
        `${t}sheet:SetAttribute(${luauStr(name)}, ${serializeTokenValue(value)})`,
      );
    }
    lines.push("");
  }

  // Rules
  for (const rule of ir.rules) {
    emitRule(rule, lines, t);
  }

  // Themes
  if (ir.themes && ir.themes.size > 0) {
    emitThemes(ir, lines, t);
  }

  lines.push(`${t}return sheet`);
  lines.push("end");
  lines.push("");
  lines.push("return createStyleSheet");
  lines.push("");

  return lines.join("\n");
}

function emitRule(rule: StyleRuleIR, lines: string[], t: string): void {
  const t2 = t + t;

  lines.push(`${t}-- Rule: ${rule.selector}`);
  lines.push(`${t}do`);
  lines.push(`${t2}local rule = Instance.new("StyleRule")`);
  lines.push(`${t2}rule.Selector = ${luauStr(rule.selector)}`);
  lines.push(`${t2}rule.Parent = sheet`);

  if (rule.properties.size === 1) {
    const [propName, propValue] = [...rule.properties.entries()][0]!;
    lines.push(
      `${t2}rule:SetProperty(${luauStr(propName)}, ${serializeRobloxValue(propValue)})`,
    );
  } else if (rule.properties.size > 1) {
    lines.push(`${t2}rule:SetProperties({`);
    for (const [propName, propValue] of rule.properties) {
      lines.push(
        `${t2}${t}${propName} = ${serializeRobloxValue(propValue)},`,
      );
    }
    lines.push(`${t2}})`);
  }

  lines.push(`${t}end`);
  lines.push("");
}

function emitThemes(ir: StyleSheetIR, lines: string[], t: string): void {
  if (!ir.themes) return;
  const t2 = t + t;

  lines.push(`${t}-- Themes`);
  lines.push(`${t}local themes = {}`);
  lines.push("");

  for (const [themeName, themeIR] of ir.themes) {
    lines.push(`${t}do`);
    lines.push(`${t2}local theme = Instance.new("StyleSheet")`);
    lines.push(`${t2}theme.Name = ${luauStr(themeIR.name)}`);
    for (const [tokenName, tokenValue] of themeIR.tokens) {
      lines.push(
        `${t2}theme:SetAttribute(${luauStr(tokenName)}, ${serializeTokenValue(tokenValue)})`,
      );
    }
    lines.push(`${t2}themes[${luauStr(themeName)}] = theme`);
    lines.push(`${t}end`);
    lines.push("");
  }

  lines.push(`${t}-- Theme derive`);
  lines.push(`${t}local themeDerive = Instance.new("StyleDerive")`);
  lines.push(`${t}themeDerive.Parent = sheet`);
  lines.push("");
  lines.push(`${t}-- Theme switcher`);
  lines.push(`${t}local function setTheme(themeName: string)`);
  lines.push(`${t2}themeDerive.StyleSheet = themes[themeName]`);
  lines.push(`${t}end`);
  lines.push("");
}

function serializeRobloxValue(value: RobloxValue): string {
  switch (value.type) {
    case "Color3":
      return `Color3.fromRGB(${value.value[0]}, ${value.value[1]}, ${value.value[2]})`;
    case "UDim2":
      return `UDim2.new(${value.value.join(", ")})`;
    case "UDim":
      return `UDim.new(${value.value.join(", ")})`;
    case "number":
      return formatNumber(value.value);
    case "boolean":
      return String(value.value);
    case "Enum":
      return `Enum.${value.enum}.${value.value}`;
    case "token":
      return `"$${value.name}"`;
    case "Font":
      return serializeFont(value);
    case "Vector2":
      return `Vector2.new(${value.value.map(formatNumber).join(", ")})`;
    case "string":
      return luauStr(value.value);
    case "ColorSequence":
      return serializeColorSequence(value.stops);
  }
}

function serializeFont(font: {
  family: string;
  weight?: string;
  style?: string;
}): string {
  const path = `rbxasset://fonts/families/${font.family}.json`;
  const args: string[] = [luauStr(path)];
  if (font.weight && font.weight !== "Regular") {
    args.push(`Enum.FontWeight.${font.weight}`);
  }
  if (font.style && font.style !== "Normal") {
    if (args.length === 1) {
      args.push("Enum.FontWeight.Regular");
    }
    args.push(`Enum.FontStyle.${font.style}`);
  }
  return `Font.new(${args.join(", ")})`;
}

function serializeColorSequence(
  stops: Array<{ position: number; color: [number, number, number] }>,
): string {
  if (stops.length === 2 && stops[0]!.position === 0 && stops[1]!.position === 1) {
    return `ColorSequence.new(Color3.fromRGB(${stops[0]!.color.join(", ")}), Color3.fromRGB(${stops[1]!.color.join(", ")}))`;
  }

  const keypoints = stops
    .map(
      (s) =>
        `ColorSequenceKeypoint.new(${formatNumber(s.position)}, Color3.fromRGB(${s.color.join(", ")}))`,
    )
    .join(", ");
  return `ColorSequence.new({${keypoints}})`;
}

function serializeTokenValue(value: TokenValue): string {
  switch (value.type) {
    case "Color3":
      return `Color3.fromHex(${luauStr(rgbToHex(value.value))})`;
    case "UDim":
      return `UDim.new(${value.value.join(", ")})`;
    case "number":
      return formatNumber(value.value);
    case "Font":
      return serializeFont(value);
    case "string":
      return luauStr(value.value);
  }
}

function luauStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function formatNumber(n: number): string {
  if (n === Infinity) return "math.huge";
  if (n === -Infinity) return "-math.huge";
  if (Number.isInteger(n)) return String(n);
  // Avoid overly precise floats
  const s = n.toPrecision(10);
  return parseFloat(s).toString();
}
