import { describe, test, expect } from "bun:test";
import { compileCss } from "../helpers.ts";
import { generateLuau } from "../../src/codegen/luau.ts";
import { generateRBXMX } from "../../src/codegen/rbxmx.ts";

describe("Luau codegen", () => {
  test("single-property rule uses SetProperty", () => {
    const result = compileCss(`.a { color: white; }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("SetProperty(");
    expect(luau).not.toContain("SetProperties(");
  });

  test("multi-property rule uses SetProperties", () => {
    const result = compileCss(`.a { color: white; font-size: 16px; }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("SetProperties({");
  });

  test("header comment includes source file", () => {
    const result = compileCss(`.a { color: white; }`);
    const luau = generateLuau(result.ir, { minify: false, sourceFile: "my-styles.css" });
    expect(luau).toContain("-- Auto-generated by rbx-css");
    expect(luau).toContain("-- Source: my-styles.css");
  });

  test("minified output has no comments", () => {
    const result = compileCss(`.a { color: white; }`);
    const luau = generateLuau(result.ir, { minify: true });
    expect(luau).not.toContain("-- Auto-generated");
    expect(luau).not.toContain("-- Source:");
  });

  test("module structure", () => {
    const result = compileCss(`.a { color: white; }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("local function createStyleSheet()");
    expect(luau).toContain("return sheet");
    expect(luau).toContain("return createStyleSheet");
  });

  test("stylesheet name is set", () => {
    const result = compileCss(`.a { color: white; }`, { name: "MySheet" });
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain('sheet.Name = "MySheet"');
  });

  test("do/end blocks scope rules", () => {
    const result = compileCss(`.a { color: white; }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("do");
    expect(luau).toContain("end");
  });

  test("Infinity serializes as math.huge", () => {
    const result = compileCss(`.a { max-height: 300px; }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("math.huge");
  });

  test("boolean value serializes correctly", () => {
    const result = compileCss(`.a { display: none; }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("false");
  });

  test("Enum values serialize correctly", () => {
    const result = compileCss(`.a { text-align: center; }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("Enum.TextXAlignment.Center");
  });

  test("string values are properly escaped", () => {
    const result = compileCss(`.a { background-image: url("rbxassetid://12345"); }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("rbxassetid://12345");
  });
});

describe("Luau codegen: ColorSequence", () => {
  test("2-stop gradient uses shorthand constructor", () => {
    const result = compileCss(`.a { background: linear-gradient(90deg, #ff0000, #0000ff); }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("ColorSequence.new(Color3.fromRGB(");
    expect(luau).not.toContain("ColorSequenceKeypoint");
  });

  test("3+ stop gradient uses keypoint constructor", () => {
    const result = compileCss(`.a { background: linear-gradient(90deg, red, green, blue); }`);
    const luau = generateLuau(result.ir, { minify: false });
    expect(luau).toContain("ColorSequenceKeypoint.new(");
  });
});

describe("RBXMX codegen", () => {
  test("produces valid XML structure", () => {
    const result = compileCss(`.a { color: white; }`);
    const rbxmx = generateRBXMX(result.ir);
    expect(rbxmx).toContain('<roblox version="4">');
    expect(rbxmx).toContain('class="StyleSheet"');
    expect(rbxmx).toContain('class="StyleRule"');
    expect(rbxmx).toContain("</roblox>");
  });

  test("stylesheet name appears in RBXMX", () => {
    const result = compileCss(`.a { color: white; }`, { name: "MySheet" });
    const rbxmx = generateRBXMX(result.ir);
    expect(rbxmx).toContain('<string name="Name">MySheet</string>');
  });

  test("selector appears in RBXMX", () => {
    const result = compileCss(`.card { color: white; }`);
    const rbxmx = generateRBXMX(result.ir);
    expect(rbxmx).toContain('<string name="Selector">.card</string>');
  });

  test("tokens listed as comments", () => {
    const result = compileCss(`:root { --bg: #335fff; }`);
    const rbxmx = generateRBXMX(result.ir);
    expect(rbxmx).toContain("<!-- Tokens -->");
    expect(rbxmx).toContain("bg:");
  });

  test("XML special characters are escaped", () => {
    const result = compileCss(`.a > .b { color: white; }`);
    const rbxmx = generateRBXMX(result.ir);
    expect(rbxmx).toContain(".a &gt; .b");
  });

  test("theme sheets in RBXMX", () => {
    const css = `
      :root { --bg: #fff; }
      [data-theme="dark"] { --bg: #000; }
    `;
    const result = compileCss(css);
    const rbxmx = generateRBXMX(result.ir);
    expect(rbxmx).toContain("Test_dark");
    // Two StyleSheet items
    const sheetCount = (rbxmx.match(/class="StyleSheet"/g) || []).length;
    expect(sheetCount).toBe(2);
  });

  test("unique referent IDs", () => {
    const result = compileCss(`.a { color: white; } .b { color: black; }`);
    const rbxmx = generateRBXMX(result.ir);
    const referents = rbxmx.match(/referent="(RBX\d+)"/g) || [];
    const unique = new Set(referents);
    expect(unique.size).toBe(referents.length);
  });
});
